application: billy-cx
version: 5
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: .*
  script: app.py

- url: /(.*)
  script: app.py

# - url: .*
#   script: main.py

# - url: /(.*)
#   script: main.py


libraries:

- name: jinja2
  version:  "2.6"





#- url: /(.*)
# script: billy-cx.app



